name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v2
      with:
        name: sigpgate-$GITHUB_REF
        path: target/release/sigpgate
